export const setup_types = {
  LOAD_ACCOUNTS: 'LOAD_ACCOUNTS',
  ACCOUNT_EXPIRES: 'ACCOUNT_EXPIRES',
  CHANGE_ACCOUNT: 'CHANGE_ACCOUNT',
  REMOVE_ACCOUNT: 'REMOVE_ACCOUNT',
};

export const nav_types = {
  CHANGE_NAV: 'CHANGE_NAV',
  CHANGE_SUB_NAV: 'CHANGE_SUB_NAV',
};

export const form_types = {
  SEND_SUCCESS: 'SEND_SUCCESS',
};
